server:
  port: 8080
  servlet:
    session:
      timeout: 30
#  ssl:
#    enabled: true
#    key-alias: ayokeystore
#    key-store: ayokeystore.pkcs12
#    key-store-password: 123456
#    key-password: 123456
#    trust-store: ayotrust.pkcs12
#    trust-store-password: 123456

spring:
  thymeleaf:
    cache: false

  datasource:
    url: jdbc:mssql://localshot/db
    username: test
    password: test
    driver-class-name: com
